name: Update Version

on:
  pull_request:
    types: unlabeled

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check if "preview" was removed
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          pr=${{ github.event.number }}
          label=$(gh api "repos/$GITHUB_REPOSITORY/issues/$pr/events" \
              --jq 'map(select(.event == "unlabeled"))[-1].label.name')

          if [[ $label == 'status:version-blocked' ]];
          then
              echo "The 'status:version-blocked' label has been removed"
          else
              echo "The 'status:version-blocked' label has not been removed"
              exit -1
          fi

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Update Version
        run: |
          git fetch origin ${GITHUB_HEAD_REF}
          git checkout ${GITHUB_HEAD_REF}
          npx changeset version
          echo "Updated changelog"
          npm i --package-lock-only
          echo "Updated lockfile"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add package*.json CHANGELOG.md .changeset
          git commit -m "Update version"
          echo "Commit changes"

      - name: Push to Branch
        run: |
          git status
          git pull
          git status
          git push
          git status